spring.application.name=manhwaapi
server.port=8080
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbap
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
jwt.secret=7f3c9a2e8b1d4f6a0c5e7b9d2a8f1c6e4b0d9a3f7c2e5b8d1a6f9c4e7b2d5a8

